# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "random_youtube_comment"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin Rymer"]
  s.date = "2012-09-27"
  s.description = "Retrieves a (psuedo)random comment from a (psuedo)random video using the Wordnik API to get a random word, search YouTube for that word, get a random search result with comments, and then get a random comment from that result. Ugly, but it works. Usually."
  s.email = "colin.rymer@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "UNLICENSE.txt",
    "VERSION",
    "lib/random_youtube_comment.rb",
    "lib/random_youtube_comment/comment.rb",
    "lib/random_youtube_comment/configuration.rb",
    "lib/random_youtube_comment/version.rb",
    "lib/random_youtube_comment/wordnik_client.rb",
    "lib/random_youtube_comment/youtube_client.rb",
    "random_youtube_comment.gemspec",
    "spec/random_youtube_comment/comment_spec.rb",
    "spec/random_youtube_comment/wordnik_client_spec.rb",
    "spec/random_youtube_comment/youtube_client_spec.rb",
    "spec/random_youtube_comment_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/crymer11/random_youtube_comment"
  s.licenses = ["UNLICENSE"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Retrieves a (psuedo)random comment from a (psuedo)random video."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<youtube_it>, [">= 0"])
      s.add_runtime_dependency(%q<wordnik>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
    else
      s.add_dependency(%q<youtube_it>, [">= 0"])
      s.add_dependency(%q<wordnik>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<youtube_it>, [">= 0"])
    s.add_dependency(%q<wordnik>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
  end
end

